# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_item2(object):
    def setupUi(self, item2):
        item2.setObjectName("item2")
        item2.resize(489, 284)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item2.setFont(font)
        item2.setStyleSheet("background-color: gray;\n"
"border-radius: 10px;")
        self.gridLayout = QtWidgets.QGridLayout(item2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QGroupBox(item2)
        self.widget.setMinimumSize(QtCore.QSize(60, 60))
        self.widget.setMaximumSize(QtCore.QSize(400, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("border: white;")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        self.btn_delete.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton {\n"
"background-color: #E42A2A;\n"
"border: 2px solid red;\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: red;\n"
"border: 2px solid red;\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout_2.addWidget(self.btn_delete, 3, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setMaximumSize(QtCore.QSize(600, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(item2)
        QtCore.QMetaObject.connectSlotsByName(item2)

    def retranslateUi(self, item2):
        _translate = QtCore.QCoreApplication.translate
        item2.setWindowTitle(_translate("item2", "Form"))
        self.widget.setTitle(_translate("item2", "GroupBox"))
        self.btn_delete.setText(_translate("item2", "Удалить"))
        self.label_2.setText(_translate("item2", "TextLabel"))
        self.label.setText(_translate("item2", "TextLabel"))
